use_frameworks!

target 'GoReactive_Example' do
  pod 'GoReactive', :path => '../'
end

target 'GoReactive_Tests' do
  pod 'GoReactiveTests', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'GoReactive' || target.name == 'GoReactiveTests'
      target.build_configurations.each do |config|
        if config.name == 'Debug'
          config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_REFERENCE_COUNT']
        end
      end
    end
  end
end
