# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
cache: cocoapods
podfile: Example/Podfile
xcode_workspace: Example/GoReactive.xcworkspace
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
xcode_scheme: GoReactive_Tests
xcode_sdk: iphonesimulator12.1

before_install:
  - gem install cocoapods --pre # Since Travis is not always on latest version
  - pod install --project-directory=Example
stages:
  - Build+Tests
  - name: PodLint
    if: type = pull_request
jobs:
  include:
    - stage: Build+Tests
      name: "Build+Tests"
      script:
        - echo xcodebuild -enableCodeCoverage YES -workspace "$TRAVIS_XCODE_WORKSPACE" -destination "$TRAVIS_XCODE_DESTINATION" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$TRAVIS_XCODE_SDK" test ONLY_ACTIVE_ARCH=NO | xcpretty -c
        - xcodebuild -enableCodeCoverage YES -workspace "$TRAVIS_XCODE_WORKSPACE" -destination "$TRAVIS_XCODE_DESTINATION" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$TRAVIS_XCODE_SDK" test ONLY_ACTIVE_ARCH=NO | xcpretty -c
    - stage: PodLint
      name: "PodLint"
      script: if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then pod lib lint --verbose; fi
